import os
import datetime
import sqlite3
import json
import requests
from cache import cache_get, cache_set, init_db, DB_PATH, LOCAL_USER_ID
from dotenv import load_dotenv
from .enrichment import add_known_entity
from .scoring import NOISE_TAGS

load_dotenv()
OTX_API_KEY = os.getenv("OTX_API_KEY")

BASE_URL_OTX = "https://otx.alienvault.com/api/v1"
headers_OTX  = {"X-OTX-API-KEY": OTX_API_KEY}

# AlienVault OTX

# Substrings in a pulse name that mark it as auto-generated noise.
# Checked case-insensitively. A pulse matching any of these gets no score weight.
_NOISE_NAME_FRAGMENTS = (
    "auto-generated pulse",
    "auto generated pulse",
    "autogenerated pulse",
    "clone",
)


def _pulse_cache_get(pulse_id):
    """Return cached pulse detail if present and younger than 24 hours; else None."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT result, cached_at FROM cache WHERE ioc = ? AND source = ?",
        (pulse_id, "otx_pulse"),
    )
    row = cursor.fetchone()
    conn.close()
    if row is None:
        return None
    cached_at = datetime.datetime.fromisoformat(row[1])
    if (datetime.datetime.now() - cached_at).total_seconds() > 86400:
        return None
    print(f"  [CACHE HIT] otx_pulse — {pulse_id}")
    return json.loads(row[0])


def _pulse_cache_set(pulse_id, data):
    cache_set(pulse_id, "otx_pulse", data)


def _fetch_pulse_detail(pulse_id):
    """Fetch full detail for one OTX pulse. Returns extracted-field dict or None on error."""
    cached = _pulse_cache_get(pulse_id)
    if cached is not None:
        return cached

    url = f"{BASE_URL_OTX}/pulses/{pulse_id}"
    try:
        resp = requests.get(url, headers=headers_OTX)
    except requests.exceptions.ConnectionError as exc:
        print(f"  [OTX] Pulse {pulse_id} fetch error ({exc}) — skipping, continuing scan")
        return None

    if resp.status_code != 200:
        print(f"  [OTX] Pulse {pulse_id} returned {resp.status_code} — skipping, continuing scan")
        return None

    d = resp.json()

    # Older pulses used singular "attack_id"; prefer the plural list, fall back to singular
    raw_attacks = d.get("attack_ids") or d.get("attack_id") or []
    attack_ids = []
    for item in raw_attacks:
        if isinstance(item, dict):
            tech_id = item.get("id") or item.get("display_name") or ""
        else:
            tech_id = str(item)
        if tech_id:
            attack_ids.append(tech_id)

    description = (d.get("description") or "").strip()[:600]

    references = [r for r in (d.get("references") or []) if r][:5]

    malware_families_raw = d.get("malware_families") or []
    malware_families = []
    for f in malware_families_raw:
        if isinstance(f, dict):
            name = f.get("display_name") or f.get("family") or ""
        else:
            name = str(f)
        if name:
            malware_families.append(name)

    targeted_countries = [c for c in (d.get("targeted_countries") or []) if c]

    author_name = d.get("author_name") or ""
    if not author_name and isinstance(d.get("author"), dict):
        author_name = d["author"].get("username") or ""

    modified = ""
    modified_raw = d.get("modified") or ""
    if modified_raw:
        try:
            modified = datetime.datetime.fromisoformat(
                modified_raw.replace("Z", "")[:19]
            ).strftime("%Y-%m-%d")
        except ValueError:
            modified = modified_raw[:10]

    detail = {
        "description":        description,
        "references":         references,
        "malware_families":   malware_families,
        "attack_ids":         attack_ids,
        "targeted_countries": targeted_countries,
        "author_name":        author_name,
        "modified":           modified,
    }

    _pulse_cache_set(pulse_id, detail)
    return detail


def _parse_modified(pulse):
    m = pulse.get("modified") or ""
    if not m:
        return datetime.datetime.min
    try:
        return datetime.datetime.fromisoformat(m.replace("Z", "")[:19])
    except ValueError:
        return datetime.datetime.min


def otx_check(indicator, ind_type, skip_passive_dns=False, user_id=LOCAL_USER_ID):

    cached = cache_get(indicator, "otx", user_id)
    if cached:
        return cached

    if ind_type == "ip":
        otx_type = "IPv4"
    elif ind_type == "hash":
        otx_type = "file"
    else:
        # Root domains have 2 parts (google.com), subdomains have 3+ (mail.google.com)
        parts = indicator.split(".")
        otx_type = "hostname" if len(parts) > 2 else "domain"
    url = f"{BASE_URL_OTX}/indicators/{otx_type}/{indicator}/general"
    try:
        response = requests.get(url, headers=headers_OTX)
    except requests.exceptions.ConnectionError:
        print("  [OTX] Connection error, check your network")
        return None

    if response.status_code == 404:
        print("  [OTX] No record found")
        return None
    if response.status_code == 429:
        print("  [OTX] Rate limit hit")
        return None
    if response.status_code != 200:
        print(f"  [OTX] Error {response.status_code}: {response.text[:200]}")
        return None

    data = response.json()

    ind_desc = data.get("description", "").strip()
    if not ind_desc:
        ind_desc = data.get("base_indicator", {}).get("description", "").strip()
    ind_desc  = ind_desc[:800] if ind_desc else None
    ind_title = data.get("base_indicator", {}).get("title", "").strip() or None

    passive_dns = []
    if not skip_passive_dns and ind_type in ("ip", "domain"):
        pdns_url = f"{BASE_URL_OTX}/indicators/{otx_type}/{indicator}/passive_dns"
        try:
            pdns_resp = requests.get(pdns_url, headers=headers_OTX)
        except requests.exceptions.ConnectionError:
            pdns_resp = None

        if pdns_resp and pdns_resp.status_code == 200:
            for record in pdns_resp.json().get("passive_dns", []):
                passive_dns.append({
                    "hostname":    record.get("hostname", ""),
                    "address":     record.get("address", ""),
                    "record_type": record.get("record_type", ""),
                    "first":       record.get("first", ""),
                    "last":        record.get("last", ""),
                })

    pulse_info = data.get("pulse_info", {})
    pulses = pulse_info.get("pulses", [])
    pulse_count = pulse_info.get("count", 0)
    pulse_details = []
    first_five = pulses[:5]

    for p in first_five:
        pulse_name = p.get("name", "Unnamed")
        adversary  = p.get("adversary", "")
        tags       = p.get("tags", [])

        malware_families_raw = p.get("malware_families", [])
        families = []
        for f in malware_families_raw:
            family_name = f["display_name"]
            families.append(family_name)

        references = p.get("references", [])
        if len(references) > 0:
            first_ref = references[0]
        else:
            first_ref = ""

        one_pulse = {
            "name":      pulse_name,
            "adversary": adversary,
            "families":  families,
            "tags":      tags,
            "ref":       first_ref,
            "description": p.get("description", "").strip()[:600],

        }
        pulse_details.append(one_pulse)

    # Filter noise pulses, sort by modified date, fetch full detail for up to 5.
    # A pulse is noise if EITHER its tags are entirely noise-tagged OR its name
    # contains a known auto-generated fragment (e.g. "clone", "Auto-generated Pulse").
    def _is_noise_pulse(p):
        p_tags = {t.lower() for t in p.get("tags", [])}
        if p_tags and p_tags.issubset(NOISE_TAGS):
            return True
        name_lower = p.get("name", "").lower()
        if any(frag in name_lower for frag in _NOISE_NAME_FRAGMENTS):
            return True
        return False

    non_noise = [p for p in pulses if not _is_noise_pulse(p)]
    non_noise_count = len(non_noise)  # accurate count from full pulse list, not just sample

    non_noise.sort(key=_parse_modified, reverse=True)
    top_for_detail = non_noise[:5]

    pulses_detail = []
    for p in top_for_detail:
        pulse_id = p.get("id")
        if not pulse_id:
            continue
        detail = _fetch_pulse_detail(str(pulse_id))
        if detail is None:
            detail = {}
        merged = {**p, **detail}
        pulses_detail.append(merged)

        try:
            for fam in (merged.get("malware_families") or []):
                add_known_entity(fam, "malware", source="otx")
            adversary = merged.get("adversary") or ""
            if adversary.strip():
                add_known_entity(adversary, "apt_actor", source="otx")
        except Exception:
            pass

    # Deduplicated cross-pulse ATT&CK techniques, malware families, targeted countries
    seen_attacks   = set()
    seen_families  = set()
    seen_countries = set()
    all_attacks    = []
    all_families   = []
    all_countries  = []

    for entry in pulses_detail:
        for aid in (entry.get("attack_ids") or []):
            if aid and aid not in seen_attacks:
                all_attacks.append(aid)
                seen_attacks.add(aid)
        for fam in (entry.get("malware_families") or []):
            if fam and fam not in seen_families:
                all_families.append(fam)
                seen_families.add(fam)
        for country in (entry.get("targeted_countries") or []):
            if country and country not in seen_countries:
                all_countries.append(country)
                seen_countries.add(country)

    breakdown = []
    if all_attacks:
        breakdown.append(f"ATT&CK techniques observed: {', '.join(all_attacks)}")
    if all_families:
        breakdown.append(f"Malware families: {', '.join(all_families)}")
    if all_countries:
        breakdown.append(f"Targeted countries: {', '.join(all_countries)}")

    reputation_threat_score = None
    reputation_threat_type  = None
    reputation_counts       = None

    if ind_type != "hash":
        rep_cached = cache_get(indicator, "otx_reputation")
        if rep_cached is not None:
            reputation_threat_score = rep_cached.get("reputation_threat_score")
            reputation_threat_type  = rep_cached.get("reputation_threat_type")
            reputation_counts       = rep_cached.get("reputation_counts")
        else:
            rep_url = f"{BASE_URL_OTX}/indicators/{otx_type}/{indicator}/reputation"
            try:
                rep_resp = requests.get(rep_url, headers=headers_OTX)
            except requests.exceptions.ConnectionError as exc:
                print(f"  [OTX] Reputation fetch error ({exc}) — skipping, continuing scan")
                rep_resp = None

            if rep_resp is not None:
                if rep_resp.status_code == 404:
                    print(f"  [OTX] Reputation not found — skipping, continuing scan")
                elif rep_resp.status_code != 200:
                    print(f"  [OTX] Reputation returned {rep_resp.status_code} — skipping, continuing scan")
                else:
                    rep_data = rep_resp.json()
                    reputation_threat_score = rep_data.get("threat_score", None)
                    reputation_threat_type  = rep_data.get("threat_type", None)
                    reputation_counts       = rep_data.get("counts", None)
                    cache_set(indicator, "otx_reputation", {
                        "reputation_threat_score": reputation_threat_score,
                        "reputation_threat_type":  reputation_threat_type,
                        "reputation_counts":       reputation_counts,
                    })

    result = {
        "pulse_count":             pulse_count,
        "non_noise_count":         non_noise_count,
        "pulse_details":           pulse_details,
        "pulses_detail":           pulses_detail,
        "passive_dns":             passive_dns,
        "breakdown":               breakdown,
        "indicator_description":   ind_desc,
        "indicator_title":         ind_title,
        "reputation_threat_score": reputation_threat_score,
        "reputation_threat_type":  reputation_threat_type,
        "reputation_counts":       reputation_counts,
    }

    if ind_type == "ip":
        result["country"]    = data.get("country_name", "Unknown")
        result["asn"]        = data.get("asn", "Unknown")
        result["reputation"] = data.get("reputation", 0)
    else:
        result["reputation"] = data.get("reputation", 0)

    cache_set(indicator, "otx", result, user_id)
    return result